# Streamlit 설정 v2.3.1

[browser]
gatherUsageStats = false

[server]
# ✅ v2.3.1: CORS/XSRF 충돌 해결 (로컬 개발 환경)
enableXsrfProtection = false
enableCORS = false

# 배포 환경에서는 아래 설정 사용:
# enableXsrfProtection = true
# enableCORS = true
# allowedOrigins = ["https://yourdomain.com"]

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
