# ✅ Streamlit 보안 설정 (외부 노출 방지)

[server]
# 로컬호스트만 허용 (외부 접근 차단)
address = "127.0.0.1"
port = 8501

# 헤드리스 모드
headless = true

# 파일 감시 최적화 (불필요한 리로드 방지)
fileWatcherType = "none"

# CORS 비활성화 (보안 강화)
enableCORS = false

# XSRF 보호 활성화
enableXsrfProtection = true

# WebSocket 압축 (성능 향상)
enableWebsocketCompression = true

[browser]
# 자동 브라우저 열기 비활성화
gatherUsageStats = false

[logger]
# 로그 레벨 (INFO 권장)
level = "info"

